package com.google.android.gms.internal.mlkit_vision_face;

import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;
import java.io.IOException;

final class zzgq implements ObjectEncoder {
    private static final FieldDescriptor zzA;
    private static final FieldDescriptor zzB;
    private static final FieldDescriptor zzC;
    private static final FieldDescriptor zzD;
    private static final FieldDescriptor zzE;
    private static final FieldDescriptor zzF;
    private static final FieldDescriptor zzG;
    private static final FieldDescriptor zzH;
    private static final FieldDescriptor zzI;
    private static final FieldDescriptor zzJ;
    private static final FieldDescriptor zzK;
    private static final FieldDescriptor zzL;
    private static final FieldDescriptor zzM;
    private static final FieldDescriptor zzN;
    private static final FieldDescriptor zzO;
    private static final FieldDescriptor zzP;
    private static final FieldDescriptor zzQ;
    private static final FieldDescriptor zzR;
    private static final FieldDescriptor zzS;
    private static final FieldDescriptor zzT;
    private static final FieldDescriptor zzU;
    private static final FieldDescriptor zzV;
    private static final FieldDescriptor zzW;
    private static final FieldDescriptor zzX;
    private static final FieldDescriptor zzY;
    private static final FieldDescriptor zzZ;
    static final zzgq zza = new zzgq();
    private static final FieldDescriptor zzaa;
    private static final FieldDescriptor zzab;
    private static final FieldDescriptor zzac;
    private static final FieldDescriptor zzad;
    private static final FieldDescriptor zzae;
    private static final FieldDescriptor zzaf;
    private static final FieldDescriptor zzag;
    private static final FieldDescriptor zzah;
    private static final FieldDescriptor zzai;
    private static final FieldDescriptor zzaj;
    private static final FieldDescriptor zzak;
    private static final FieldDescriptor zzal;
    private static final FieldDescriptor zzam;
    private static final FieldDescriptor zzan;
    private static final FieldDescriptor zzao;
    private static final FieldDescriptor zzap;
    private static final FieldDescriptor zzaq;
    private static final FieldDescriptor zzar;
    private static final FieldDescriptor zzas;
    private static final FieldDescriptor zzat;
    private static final FieldDescriptor zzau;
    private static final FieldDescriptor zzav;
    private static final FieldDescriptor zzaw;
    private static final FieldDescriptor zzax;
    private static final FieldDescriptor zzay;
    private static final FieldDescriptor zzb;
    private static final FieldDescriptor zzc;
    private static final FieldDescriptor zzd;
    private static final FieldDescriptor zze;
    private static final FieldDescriptor zzf;
    private static final FieldDescriptor zzg;
    private static final FieldDescriptor zzh;
    private static final FieldDescriptor zzi;
    private static final FieldDescriptor zzj;
    private static final FieldDescriptor zzk;
    private static final FieldDescriptor zzl;
    private static final FieldDescriptor zzm;
    private static final FieldDescriptor zzn;
    private static final FieldDescriptor zzo;
    private static final FieldDescriptor zzp;
    private static final FieldDescriptor zzq;
    private static final FieldDescriptor zzr;
    private static final FieldDescriptor zzs;
    private static final FieldDescriptor zzt;
    private static final FieldDescriptor zzu;
    private static final FieldDescriptor zzv;
    private static final FieldDescriptor zzw;
    private static final FieldDescriptor zzx;
    private static final FieldDescriptor zzy;
    private static final FieldDescriptor zzz;

    static {
        FieldDescriptor.Builder builder = FieldDescriptor.builder("systemInfo");
        zzcq zzcq = new zzcq();
        zzcq.zza(1);
        zzb = builder.withProperty(zzcq.zzb()).build();
        FieldDescriptor.Builder builder2 = FieldDescriptor.builder("eventName");
        zzcq zzcq2 = new zzcq();
        zzcq2.zza(2);
        zzc = builder2.withProperty(zzcq2.zzb()).build();
        FieldDescriptor.Builder builder3 = FieldDescriptor.builder("isThickClient");
        zzcq zzcq3 = new zzcq();
        zzcq3.zza(37);
        zzd = builder3.withProperty(zzcq3.zzb()).build();
        FieldDescriptor.Builder builder4 = FieldDescriptor.builder("clientType");
        zzcq zzcq4 = new zzcq();
        zzcq4.zza(61);
        zze = builder4.withProperty(zzcq4.zzb()).build();
        FieldDescriptor.Builder builder5 = FieldDescriptor.builder("modelDownloadLogEvent");
        zzcq zzcq5 = new zzcq();
        zzcq5.zza(3);
        zzf = builder5.withProperty(zzcq5.zzb()).build();
        FieldDescriptor.Builder builder6 = FieldDescriptor.builder("customModelLoadLogEvent");
        zzcq zzcq6 = new zzcq();
        zzcq6.zza(20);
        zzg = builder6.withProperty(zzcq6.zzb()).build();
        FieldDescriptor.Builder builder7 = FieldDescriptor.builder("customModelInferenceLogEvent");
        zzcq zzcq7 = new zzcq();
        zzcq7.zza(4);
        zzh = builder7.withProperty(zzcq7.zzb()).build();
        FieldDescriptor.Builder builder8 = FieldDescriptor.builder("customModelCreateLogEvent");
        zzcq zzcq8 = new zzcq();
        zzcq8.zza(29);
        zzi = builder8.withProperty(zzcq8.zzb()).build();
        FieldDescriptor.Builder builder9 = FieldDescriptor.builder("onDeviceFaceDetectionLogEvent");
        zzcq zzcq9 = new zzcq();
        zzcq9.zza(5);
        zzj = builder9.withProperty(zzcq9.zzb()).build();
        FieldDescriptor.Builder builder10 = FieldDescriptor.builder("onDeviceFaceLoadLogEvent");
        zzcq zzcq10 = new zzcq();
        zzcq10.zza(59);
        zzk = builder10.withProperty(zzcq10.zzb()).build();
        FieldDescriptor.Builder builder11 = FieldDescriptor.builder("onDeviceTextDetectionLogEvent");
        zzcq zzcq11 = new zzcq();
        zzcq11.zza(6);
        zzl = builder11.withProperty(zzcq11.zzb()).build();
        FieldDescriptor.Builder builder12 = FieldDescriptor.builder("onDeviceTextDetectionLoadLogEvent");
        zzcq zzcq12 = new zzcq();
        zzcq12.zza(79);
        zzm = builder12.withProperty(zzcq12.zzb()).build();
        FieldDescriptor.Builder builder13 = FieldDescriptor.builder("onDeviceBarcodeDetectionLogEvent");
        zzcq zzcq13 = new zzcq();
        zzcq13.zza(7);
        zzn = builder13.withProperty(zzcq13.zzb()).build();
        FieldDescriptor.Builder builder14 = FieldDescriptor.builder("onDeviceBarcodeLoadLogEvent");
        zzcq zzcq14 = new zzcq();
        zzcq14.zza(58);
        zzo = builder14.withProperty(zzcq14.zzb()).build();
        FieldDescriptor.Builder builder15 = FieldDescriptor.builder("onDeviceImageLabelCreateLogEvent");
        zzcq zzcq15 = new zzcq();
        zzcq15.zza(48);
        zzp = builder15.withProperty(zzcq15.zzb()).build();
        FieldDescriptor.Builder builder16 = FieldDescriptor.builder("onDeviceImageLabelLoadLogEvent");
        zzcq zzcq16 = new zzcq();
        zzcq16.zza(49);
        zzq = builder16.withProperty(zzcq16.zzb()).build();
        FieldDescriptor.Builder builder17 = FieldDescriptor.builder("onDeviceImageLabelDetectionLogEvent");
        zzcq zzcq17 = new zzcq();
        zzcq17.zza(18);
        zzr = builder17.withProperty(zzcq17.zzb()).build();
        FieldDescriptor.Builder builder18 = FieldDescriptor.builder("onDeviceObjectCreateLogEvent");
        zzcq zzcq18 = new zzcq();
        zzcq18.zza(26);
        zzs = builder18.withProperty(zzcq18.zzb()).build();
        FieldDescriptor.Builder builder19 = FieldDescriptor.builder("onDeviceObjectLoadLogEvent");
        zzcq zzcq19 = new zzcq();
        zzcq19.zza(27);
        zzt = builder19.withProperty(zzcq19.zzb()).build();
        FieldDescriptor.Builder builder20 = FieldDescriptor.builder("onDeviceObjectInferenceLogEvent");
        zzcq zzcq20 = new zzcq();
        zzcq20.zza(28);
        zzu = builder20.withProperty(zzcq20.zzb()).build();
        FieldDescriptor.Builder builder21 = FieldDescriptor.builder("onDevicePoseDetectionLogEvent");
        zzcq zzcq21 = new zzcq();
        zzcq21.zza(44);
        zzv = builder21.withProperty(zzcq21.zzb()).build();
        FieldDescriptor.Builder builder22 = FieldDescriptor.builder("onDeviceSegmentationLogEvent");
        zzcq zzcq22 = new zzcq();
        zzcq22.zza(45);
        zzw = builder22.withProperty(zzcq22.zzb()).build();
        FieldDescriptor.Builder builder23 = FieldDescriptor.builder("onDeviceSmartReplyLogEvent");
        zzcq zzcq23 = new zzcq();
        zzcq23.zza(19);
        zzx = builder23.withProperty(zzcq23.zzb()).build();
        FieldDescriptor.Builder builder24 = FieldDescriptor.builder("onDeviceLanguageIdentificationLogEvent");
        zzcq zzcq24 = new zzcq();
        zzcq24.zza(21);
        zzy = builder24.withProperty(zzcq24.zzb()).build();
        FieldDescriptor.Builder builder25 = FieldDescriptor.builder("onDeviceTranslationLogEvent");
        zzcq zzcq25 = new zzcq();
        zzcq25.zza(22);
        zzz = builder25.withProperty(zzcq25.zzb()).build();
        FieldDescriptor.Builder builder26 = FieldDescriptor.builder("cloudFaceDetectionLogEvent");
        zzcq zzcq26 = new zzcq();
        zzcq26.zza(8);
        zzA = builder26.withProperty(zzcq26.zzb()).build();
        FieldDescriptor.Builder builder27 = FieldDescriptor.builder("cloudCropHintDetectionLogEvent");
        zzcq zzcq27 = new zzcq();
        zzcq27.zza(9);
        zzB = builder27.withProperty(zzcq27.zzb()).build();
        FieldDescriptor.Builder builder28 = FieldDescriptor.builder("cloudDocumentTextDetectionLogEvent");
        zzcq zzcq28 = new zzcq();
        zzcq28.zza(10);
        zzC = builder28.withProperty(zzcq28.zzb()).build();
        FieldDescriptor.Builder builder29 = FieldDescriptor.builder("cloudImagePropertiesDetectionLogEvent");
        zzcq zzcq29 = new zzcq();
        zzcq29.zza(11);
        zzD = builder29.withProperty(zzcq29.zzb()).build();
        FieldDescriptor.Builder builder30 = FieldDescriptor.builder("cloudImageLabelDetectionLogEvent");
        zzcq zzcq30 = new zzcq();
        zzcq30.zza(12);
        zzE = builder30.withProperty(zzcq30.zzb()).build();
        FieldDescriptor.Builder builder31 = FieldDescriptor.builder("cloudLandmarkDetectionLogEvent");
        zzcq zzcq31 = new zzcq();
        zzcq31.zza(13);
        zzF = builder31.withProperty(zzcq31.zzb()).build();
        FieldDescriptor.Builder builder32 = FieldDescriptor.builder("cloudLogoDetectionLogEvent");
        zzcq zzcq32 = new zzcq();
        zzcq32.zza(14);
        zzG = builder32.withProperty(zzcq32.zzb()).build();
        FieldDescriptor.Builder builder33 = FieldDescriptor.builder("cloudSafeSearchDetectionLogEvent");
        zzcq zzcq33 = new zzcq();
        zzcq33.zza(15);
        zzH = builder33.withProperty(zzcq33.zzb()).build();
        FieldDescriptor.Builder builder34 = FieldDescriptor.builder("cloudTextDetectionLogEvent");
        zzcq zzcq34 = new zzcq();
        zzcq34.zza(16);
        zzI = builder34.withProperty(zzcq34.zzb()).build();
        FieldDescriptor.Builder builder35 = FieldDescriptor.builder("cloudWebSearchDetectionLogEvent");
        zzcq zzcq35 = new zzcq();
        zzcq35.zza(17);
        zzJ = builder35.withProperty(zzcq35.zzb()).build();
        FieldDescriptor.Builder builder36 = FieldDescriptor.builder("automlImageLabelingCreateLogEvent");
        zzcq zzcq36 = new zzcq();
        zzcq36.zza(23);
        zzK = builder36.withProperty(zzcq36.zzb()).build();
        FieldDescriptor.Builder builder37 = FieldDescriptor.builder("automlImageLabelingLoadLogEvent");
        zzcq zzcq37 = new zzcq();
        zzcq37.zza(24);
        zzL = builder37.withProperty(zzcq37.zzb()).build();
        FieldDescriptor.Builder builder38 = FieldDescriptor.builder("automlImageLabelingInferenceLogEvent");
        zzcq zzcq38 = new zzcq();
        zzcq38.zza(25);
        zzM = builder38.withProperty(zzcq38.zzb()).build();
        FieldDescriptor.Builder builder39 = FieldDescriptor.builder("isModelDownloadedLogEvent");
        zzcq zzcq39 = new zzcq();
        zzcq39.zza(39);
        zzN = builder39.withProperty(zzcq39.zzb()).build();
        FieldDescriptor.Builder builder40 = FieldDescriptor.builder("deleteModelLogEvent");
        zzcq zzcq40 = new zzcq();
        zzcq40.zza(40);
        zzO = builder40.withProperty(zzcq40.zzb()).build();
        FieldDescriptor.Builder builder41 = FieldDescriptor.builder("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzcq zzcq41 = new zzcq();
        zzcq41.zza(30);
        zzP = builder41.withProperty(zzcq41.zzb()).build();
        FieldDescriptor.Builder builder42 = FieldDescriptor.builder("aggregatedCustomModelInferenceLogEvent");
        zzcq zzcq42 = new zzcq();
        zzcq42.zza(31);
        zzQ = builder42.withProperty(zzcq42.zzb()).build();
        FieldDescriptor.Builder builder43 = FieldDescriptor.builder("aggregatedOnDeviceFaceDetectionLogEvent");
        zzcq zzcq43 = new zzcq();
        zzcq43.zza(32);
        zzR = builder43.withProperty(zzcq43.zzb()).build();
        FieldDescriptor.Builder builder44 = FieldDescriptor.builder("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzcq zzcq44 = new zzcq();
        zzcq44.zza(33);
        zzS = builder44.withProperty(zzcq44.zzb()).build();
        FieldDescriptor.Builder builder45 = FieldDescriptor.builder("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzcq zzcq45 = new zzcq();
        zzcq45.zza(34);
        zzT = builder45.withProperty(zzcq45.zzb()).build();
        FieldDescriptor.Builder builder46 = FieldDescriptor.builder("aggregatedOnDeviceObjectInferenceLogEvent");
        zzcq zzcq46 = new zzcq();
        zzcq46.zza(35);
        zzU = builder46.withProperty(zzcq46.zzb()).build();
        FieldDescriptor.Builder builder47 = FieldDescriptor.builder("aggregatedOnDeviceTextDetectionLogEvent");
        zzcq zzcq47 = new zzcq();
        zzcq47.zza(36);
        zzV = builder47.withProperty(zzcq47.zzb()).build();
        FieldDescriptor.Builder builder48 = FieldDescriptor.builder("aggregatedOnDevicePoseDetectionLogEvent");
        zzcq zzcq48 = new zzcq();
        zzcq48.zza(46);
        zzW = builder48.withProperty(zzcq48.zzb()).build();
        FieldDescriptor.Builder builder49 = FieldDescriptor.builder("aggregatedOnDeviceSegmentationLogEvent");
        zzcq zzcq49 = new zzcq();
        zzcq49.zza(47);
        zzX = builder49.withProperty(zzcq49.zzb()).build();
        FieldDescriptor.Builder builder50 = FieldDescriptor.builder("pipelineAccelerationInferenceEvents");
        zzcq zzcq50 = new zzcq();
        zzcq50.zza(69);
        zzY = builder50.withProperty(zzcq50.zzb()).build();
        FieldDescriptor.Builder builder51 = FieldDescriptor.builder("remoteConfigLogEvent");
        zzcq zzcq51 = new zzcq();
        zzcq51.zza(42);
        zzZ = builder51.withProperty(zzcq51.zzb()).build();
        FieldDescriptor.Builder builder52 = FieldDescriptor.builder("inputImageConstructionLogEvent");
        zzcq zzcq52 = new zzcq();
        zzcq52.zza(50);
        zzaa = builder52.withProperty(zzcq52.zzb()).build();
        FieldDescriptor.Builder builder53 = FieldDescriptor.builder("leakedHandleEvent");
        zzcq zzcq53 = new zzcq();
        zzcq53.zza(51);
        zzab = builder53.withProperty(zzcq53.zzb()).build();
        FieldDescriptor.Builder builder54 = FieldDescriptor.builder("cameraSourceLogEvent");
        zzcq zzcq54 = new zzcq();
        zzcq54.zza(52);
        zzac = builder54.withProperty(zzcq54.zzb()).build();
        FieldDescriptor.Builder builder55 = FieldDescriptor.builder("imageLabelOptionalModuleLogEvent");
        zzcq zzcq55 = new zzcq();
        zzcq55.zza(53);
        zzad = builder55.withProperty(zzcq55.zzb()).build();
        FieldDescriptor.Builder builder56 = FieldDescriptor.builder("languageIdentificationOptionalModuleLogEvent");
        zzcq zzcq56 = new zzcq();
        zzcq56.zza(54);
        zzae = builder56.withProperty(zzcq56.zzb()).build();
        FieldDescriptor.Builder builder57 = FieldDescriptor.builder("faceDetectionOptionalModuleLogEvent");
        zzcq zzcq57 = new zzcq();
        zzcq57.zza(60);
        zzaf = builder57.withProperty(zzcq57.zzb()).build();
        FieldDescriptor.Builder builder58 = FieldDescriptor.builder("nlClassifierOptionalModuleLogEvent");
        zzcq zzcq58 = new zzcq();
        zzcq58.zza(55);
        zzag = builder58.withProperty(zzcq58.zzb()).build();
        FieldDescriptor.Builder builder59 = FieldDescriptor.builder("nlClassifierClientLibraryLogEvent");
        zzcq zzcq59 = new zzcq();
        zzcq59.zza(56);
        zzah = builder59.withProperty(zzcq59.zzb()).build();
        FieldDescriptor.Builder builder60 = FieldDescriptor.builder("accelerationAllowlistLogEvent");
        zzcq zzcq60 = new zzcq();
        zzcq60.zza(57);
        zzai = builder60.withProperty(zzcq60.zzb()).build();
        FieldDescriptor.Builder builder61 = FieldDescriptor.builder("toxicityDetectionCreateEvent");
        zzcq zzcq61 = new zzcq();
        zzcq61.zza(62);
        zzaj = builder61.withProperty(zzcq61.zzb()).build();
        FieldDescriptor.Builder builder62 = FieldDescriptor.builder("toxicityDetectionLoadEvent");
        zzcq zzcq62 = new zzcq();
        zzcq62.zza(63);
        zzak = builder62.withProperty(zzcq62.zzb()).build();
        FieldDescriptor.Builder builder63 = FieldDescriptor.builder("toxicityDetectionInferenceEvent");
        zzcq zzcq63 = new zzcq();
        zzcq63.zza(64);
        zzal = builder63.withProperty(zzcq63.zzb()).build();
        FieldDescriptor.Builder builder64 = FieldDescriptor.builder("barcodeDetectionOptionalModuleLogEvent");
        zzcq zzcq64 = new zzcq();
        zzcq64.zza(65);
        zzam = builder64.withProperty(zzcq64.zzb()).build();
        FieldDescriptor.Builder builder65 = FieldDescriptor.builder("customImageLabelOptionalModuleLogEvent");
        zzcq zzcq65 = new zzcq();
        zzcq65.zza(66);
        zzan = builder65.withProperty(zzcq65.zzb()).build();
        FieldDescriptor.Builder builder66 = FieldDescriptor.builder("codeScannerScanApiEvent");
        zzcq zzcq66 = new zzcq();
        zzcq66.zza(67);
        zzao = builder66.withProperty(zzcq66.zzb()).build();
        FieldDescriptor.Builder builder67 = FieldDescriptor.builder("codeScannerOptionalModuleEvent");
        zzcq zzcq67 = new zzcq();
        zzcq67.zza(68);
        zzap = builder67.withProperty(zzcq67.zzb()).build();
        FieldDescriptor.Builder builder68 = FieldDescriptor.builder("onDeviceExplicitContentCreateLogEvent");
        zzcq zzcq68 = new zzcq();
        zzcq68.zza(70);
        zzaq = builder68.withProperty(zzcq68.zzb()).build();
        FieldDescriptor.Builder builder69 = FieldDescriptor.builder("onDeviceExplicitContentLoadLogEvent");
        zzcq zzcq69 = new zzcq();
        zzcq69.zza(71);
        zzar = builder69.withProperty(zzcq69.zzb()).build();
        FieldDescriptor.Builder builder70 = FieldDescriptor.builder("onDeviceExplicitContentInferenceLogEvent");
        zzcq zzcq70 = new zzcq();
        zzcq70.zza(72);
        zzas = builder70.withProperty(zzcq70.zzb()).build();
        FieldDescriptor.Builder builder71 = FieldDescriptor.builder("aggregatedOnDeviceExplicitContentLogEvent");
        zzcq zzcq71 = new zzcq();
        zzcq71.zza(73);
        zzat = builder71.withProperty(zzcq71.zzb()).build();
        FieldDescriptor.Builder builder72 = FieldDescriptor.builder("onDeviceSelfieFaceCreateLogEvent");
        zzcq zzcq72 = new zzcq();
        zzcq72.zza(74);
        zzau = builder72.withProperty(zzcq72.zzb()).build();
        FieldDescriptor.Builder builder73 = FieldDescriptor.builder("onDeviceSelfieFaceLoadLogEvent");
        zzcq zzcq73 = new zzcq();
        zzcq73.zza(75);
        zzav = builder73.withProperty(zzcq73.zzb()).build();
        FieldDescriptor.Builder builder74 = FieldDescriptor.builder("onDeviceSelfieFaceLogEvent");
        zzcq zzcq74 = new zzcq();
        zzcq74.zza(76);
        zzaw = builder74.withProperty(zzcq74.zzb()).build();
        FieldDescriptor.Builder builder75 = FieldDescriptor.builder("aggregatedOnDeviceSelfieFaceLogEvent");
        zzcq zzcq75 = new zzcq();
        zzcq75.zza(77);
        zzax = builder75.withProperty(zzcq75.zzb()).build();
        FieldDescriptor.Builder builder76 = FieldDescriptor.builder("smartReplyOptionalModuleLogEvent");
        zzcq zzcq76 = new zzcq();
        zzcq76.zza(78);
        zzay = builder76.withProperty(zzcq76.zzb()).build();
    }

    private zzgq() {
    }

    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) throws IOException {
        zzkw zzkw = (zzkw) obj;
        ObjectEncoderContext objectEncoderContext = (ObjectEncoderContext) obj2;
        objectEncoderContext.add(zzb, (Object) zzkw.zzf());
        objectEncoderContext.add(zzc, (Object) zzkw.zzc());
        objectEncoderContext.add(zzd, (Object) null);
        objectEncoderContext.add(zze, (Object) zzkw.zzb());
        objectEncoderContext.add(zzf, (Object) null);
        objectEncoderContext.add(zzg, (Object) null);
        objectEncoderContext.add(zzh, (Object) null);
        objectEncoderContext.add(zzi, (Object) null);
        objectEncoderContext.add(zzj, (Object) zzkw.zzd());
        objectEncoderContext.add(zzk, (Object) zzkw.zze());
        objectEncoderContext.add(zzl, (Object) null);
        objectEncoderContext.add(zzm, (Object) null);
        objectEncoderContext.add(zzn, (Object) null);
        objectEncoderContext.add(zzo, (Object) null);
        objectEncoderContext.add(zzp, (Object) null);
        objectEncoderContext.add(zzq, (Object) null);
        objectEncoderContext.add(zzr, (Object) null);
        objectEncoderContext.add(zzs, (Object) null);
        objectEncoderContext.add(zzt, (Object) null);
        objectEncoderContext.add(zzu, (Object) null);
        objectEncoderContext.add(zzv, (Object) null);
        objectEncoderContext.add(zzw, (Object) null);
        objectEncoderContext.add(zzx, (Object) null);
        objectEncoderContext.add(zzy, (Object) null);
        objectEncoderContext.add(zzz, (Object) null);
        objectEncoderContext.add(zzA, (Object) null);
        objectEncoderContext.add(zzB, (Object) null);
        objectEncoderContext.add(zzC, (Object) null);
        objectEncoderContext.add(zzD, (Object) null);
        objectEncoderContext.add(zzE, (Object) null);
        objectEncoderContext.add(zzF, (Object) null);
        objectEncoderContext.add(zzG, (Object) null);
        objectEncoderContext.add(zzH, (Object) null);
        objectEncoderContext.add(zzI, (Object) null);
        objectEncoderContext.add(zzJ, (Object) null);
        objectEncoderContext.add(zzK, (Object) null);
        objectEncoderContext.add(zzL, (Object) null);
        objectEncoderContext.add(zzM, (Object) null);
        objectEncoderContext.add(zzN, (Object) null);
        objectEncoderContext.add(zzO, (Object) null);
        objectEncoderContext.add(zzP, (Object) null);
        objectEncoderContext.add(zzQ, (Object) null);
        objectEncoderContext.add(zzR, (Object) zzkw.zza());
        objectEncoderContext.add(zzS, (Object) null);
        objectEncoderContext.add(zzT, (Object) null);
        objectEncoderContext.add(zzU, (Object) null);
        objectEncoderContext.add(zzV, (Object) null);
        objectEncoderContext.add(zzW, (Object) null);
        objectEncoderContext.add(zzX, (Object) null);
        objectEncoderContext.add(zzY, (Object) null);
        objectEncoderContext.add(zzZ, (Object) null);
        objectEncoderContext.add(zzaa, (Object) null);
        objectEncoderContext.add(zzab, (Object) null);
        objectEncoderContext.add(zzac, (Object) null);
        objectEncoderContext.add(zzad, (Object) null);
        objectEncoderContext.add(zzae, (Object) null);
        objectEncoderContext.add(zzaf, (Object) null);
        objectEncoderContext.add(zzag, (Object) null);
        objectEncoderContext.add(zzah, (Object) null);
        objectEncoderContext.add(zzai, (Object) null);
        objectEncoderContext.add(zzaj, (Object) null);
        objectEncoderContext.add(zzak, (Object) null);
        objectEncoderContext.add(zzal, (Object) null);
        objectEncoderContext.add(zzam, (Object) null);
        objectEncoderContext.add(zzan, (Object) null);
        objectEncoderContext.add(zzao, (Object) null);
        objectEncoderContext.add(zzap, (Object) null);
        objectEncoderContext.add(zzaq, (Object) null);
        objectEncoderContext.add(zzar, (Object) null);
        objectEncoderContext.add(zzas, (Object) null);
        objectEncoderContext.add(zzat, (Object) null);
        objectEncoderContext.add(zzau, (Object) null);
        objectEncoderContext.add(zzav, (Object) null);
        objectEncoderContext.add(zzaw, (Object) null);
        objectEncoderContext.add(zzax, (Object) null);
        objectEncoderContext.add(zzay, (Object) null);
    }
}
