package com.google.android.gms.internal.mlkit_vision_barcode;

import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;
import java.io.IOException;

final class zzih implements ObjectEncoder {
    private static final FieldDescriptor zzA;
    private static final FieldDescriptor zzB;
    private static final FieldDescriptor zzC;
    private static final FieldDescriptor zzD;
    private static final FieldDescriptor zzE;
    private static final FieldDescriptor zzF;
    private static final FieldDescriptor zzG;
    private static final FieldDescriptor zzH;
    private static final FieldDescriptor zzI;
    private static final FieldDescriptor zzJ;
    private static final FieldDescriptor zzK;
    private static final FieldDescriptor zzL;
    private static final FieldDescriptor zzM;
    private static final FieldDescriptor zzN;
    private static final FieldDescriptor zzO;
    private static final FieldDescriptor zzP;
    private static final FieldDescriptor zzQ;
    private static final FieldDescriptor zzR;
    private static final FieldDescriptor zzS;
    private static final FieldDescriptor zzT;
    private static final FieldDescriptor zzU;
    private static final FieldDescriptor zzV;
    private static final FieldDescriptor zzW;
    private static final FieldDescriptor zzX;
    private static final FieldDescriptor zzY;
    private static final FieldDescriptor zzZ;
    static final zzih zza = new zzih();
    private static final FieldDescriptor zzaA;
    private static final FieldDescriptor zzaB;
    private static final FieldDescriptor zzaC;
    private static final FieldDescriptor zzaD;
    private static final FieldDescriptor zzaE;
    private static final FieldDescriptor zzaF;
    private static final FieldDescriptor zzaG;
    private static final FieldDescriptor zzaH;
    private static final FieldDescriptor zzaI;
    private static final FieldDescriptor zzaJ;
    private static final FieldDescriptor zzaK;
    private static final FieldDescriptor zzaL;
    private static final FieldDescriptor zzaM;
    private static final FieldDescriptor zzaN;
    private static final FieldDescriptor zzaO;
    private static final FieldDescriptor zzaP;
    private static final FieldDescriptor zzaQ;
    private static final FieldDescriptor zzaR;
    private static final FieldDescriptor zzaS;
    private static final FieldDescriptor zzaT;
    private static final FieldDescriptor zzaU;
    private static final FieldDescriptor zzaV;
    private static final FieldDescriptor zzaW;
    private static final FieldDescriptor zzaX;
    private static final FieldDescriptor zzaY;
    private static final FieldDescriptor zzaa;
    private static final FieldDescriptor zzab;
    private static final FieldDescriptor zzac;
    private static final FieldDescriptor zzad;
    private static final FieldDescriptor zzae;
    private static final FieldDescriptor zzaf;
    private static final FieldDescriptor zzag;
    private static final FieldDescriptor zzah;
    private static final FieldDescriptor zzai;
    private static final FieldDescriptor zzaj;
    private static final FieldDescriptor zzak;
    private static final FieldDescriptor zzal;
    private static final FieldDescriptor zzam;
    private static final FieldDescriptor zzan;
    private static final FieldDescriptor zzao;
    private static final FieldDescriptor zzap;
    private static final FieldDescriptor zzaq;
    private static final FieldDescriptor zzar;
    private static final FieldDescriptor zzas;
    private static final FieldDescriptor zzat;
    private static final FieldDescriptor zzau;
    private static final FieldDescriptor zzav;
    private static final FieldDescriptor zzaw;
    private static final FieldDescriptor zzax;
    private static final FieldDescriptor zzay;
    private static final FieldDescriptor zzaz;
    private static final FieldDescriptor zzb;
    private static final FieldDescriptor zzc;
    private static final FieldDescriptor zzd;
    private static final FieldDescriptor zze;
    private static final FieldDescriptor zzf;
    private static final FieldDescriptor zzg;
    private static final FieldDescriptor zzh;
    private static final FieldDescriptor zzi;
    private static final FieldDescriptor zzj;
    private static final FieldDescriptor zzk;
    private static final FieldDescriptor zzl;
    private static final FieldDescriptor zzm;
    private static final FieldDescriptor zzn;
    private static final FieldDescriptor zzo;
    private static final FieldDescriptor zzp;
    private static final FieldDescriptor zzq;
    private static final FieldDescriptor zzr;
    private static final FieldDescriptor zzs;
    private static final FieldDescriptor zzt;
    private static final FieldDescriptor zzu;
    private static final FieldDescriptor zzv;
    private static final FieldDescriptor zzw;
    private static final FieldDescriptor zzx;
    private static final FieldDescriptor zzy;
    private static final FieldDescriptor zzz;

    static {
        FieldDescriptor.Builder builder = FieldDescriptor.builder("systemInfo");
        zzdg zzdg = new zzdg();
        zzdg.zza(1);
        zzb = builder.withProperty(zzdg.zzb()).build();
        FieldDescriptor.Builder builder2 = FieldDescriptor.builder("eventName");
        zzdg zzdg2 = new zzdg();
        zzdg2.zza(2);
        zzc = builder2.withProperty(zzdg2.zzb()).build();
        FieldDescriptor.Builder builder3 = FieldDescriptor.builder("isThickClient");
        zzdg zzdg3 = new zzdg();
        zzdg3.zza(37);
        zzd = builder3.withProperty(zzdg3.zzb()).build();
        FieldDescriptor.Builder builder4 = FieldDescriptor.builder("clientType");
        zzdg zzdg4 = new zzdg();
        zzdg4.zza(61);
        zze = builder4.withProperty(zzdg4.zzb()).build();
        FieldDescriptor.Builder builder5 = FieldDescriptor.builder("modelDownloadLogEvent");
        zzdg zzdg5 = new zzdg();
        zzdg5.zza(3);
        zzf = builder5.withProperty(zzdg5.zzb()).build();
        FieldDescriptor.Builder builder6 = FieldDescriptor.builder("customModelLoadLogEvent");
        zzdg zzdg6 = new zzdg();
        zzdg6.zza(20);
        zzg = builder6.withProperty(zzdg6.zzb()).build();
        FieldDescriptor.Builder builder7 = FieldDescriptor.builder("customModelInferenceLogEvent");
        zzdg zzdg7 = new zzdg();
        zzdg7.zza(4);
        zzh = builder7.withProperty(zzdg7.zzb()).build();
        FieldDescriptor.Builder builder8 = FieldDescriptor.builder("customModelCreateLogEvent");
        zzdg zzdg8 = new zzdg();
        zzdg8.zza(29);
        zzi = builder8.withProperty(zzdg8.zzb()).build();
        FieldDescriptor.Builder builder9 = FieldDescriptor.builder("onDeviceFaceDetectionLogEvent");
        zzdg zzdg9 = new zzdg();
        zzdg9.zza(5);
        zzj = builder9.withProperty(zzdg9.zzb()).build();
        FieldDescriptor.Builder builder10 = FieldDescriptor.builder("onDeviceFaceLoadLogEvent");
        zzdg zzdg10 = new zzdg();
        zzdg10.zza(59);
        zzk = builder10.withProperty(zzdg10.zzb()).build();
        FieldDescriptor.Builder builder11 = FieldDescriptor.builder("onDeviceTextDetectionLogEvent");
        zzdg zzdg11 = new zzdg();
        zzdg11.zza(6);
        zzl = builder11.withProperty(zzdg11.zzb()).build();
        FieldDescriptor.Builder builder12 = FieldDescriptor.builder("onDeviceTextDetectionLoadLogEvent");
        zzdg zzdg12 = new zzdg();
        zzdg12.zza(79);
        zzm = builder12.withProperty(zzdg12.zzb()).build();
        FieldDescriptor.Builder builder13 = FieldDescriptor.builder("onDeviceBarcodeDetectionLogEvent");
        zzdg zzdg13 = new zzdg();
        zzdg13.zza(7);
        zzn = builder13.withProperty(zzdg13.zzb()).build();
        FieldDescriptor.Builder builder14 = FieldDescriptor.builder("onDeviceBarcodeLoadLogEvent");
        zzdg zzdg14 = new zzdg();
        zzdg14.zza(58);
        zzo = builder14.withProperty(zzdg14.zzb()).build();
        FieldDescriptor.Builder builder15 = FieldDescriptor.builder("onDeviceImageLabelCreateLogEvent");
        zzdg zzdg15 = new zzdg();
        zzdg15.zza(48);
        zzp = builder15.withProperty(zzdg15.zzb()).build();
        FieldDescriptor.Builder builder16 = FieldDescriptor.builder("onDeviceImageLabelLoadLogEvent");
        zzdg zzdg16 = new zzdg();
        zzdg16.zza(49);
        zzq = builder16.withProperty(zzdg16.zzb()).build();
        FieldDescriptor.Builder builder17 = FieldDescriptor.builder("onDeviceImageLabelDetectionLogEvent");
        zzdg zzdg17 = new zzdg();
        zzdg17.zza(18);
        zzr = builder17.withProperty(zzdg17.zzb()).build();
        FieldDescriptor.Builder builder18 = FieldDescriptor.builder("onDeviceObjectCreateLogEvent");
        zzdg zzdg18 = new zzdg();
        zzdg18.zza(26);
        zzs = builder18.withProperty(zzdg18.zzb()).build();
        FieldDescriptor.Builder builder19 = FieldDescriptor.builder("onDeviceObjectLoadLogEvent");
        zzdg zzdg19 = new zzdg();
        zzdg19.zza(27);
        zzt = builder19.withProperty(zzdg19.zzb()).build();
        FieldDescriptor.Builder builder20 = FieldDescriptor.builder("onDeviceObjectInferenceLogEvent");
        zzdg zzdg20 = new zzdg();
        zzdg20.zza(28);
        zzu = builder20.withProperty(zzdg20.zzb()).build();
        FieldDescriptor.Builder builder21 = FieldDescriptor.builder("onDevicePoseDetectionLogEvent");
        zzdg zzdg21 = new zzdg();
        zzdg21.zza(44);
        zzv = builder21.withProperty(zzdg21.zzb()).build();
        FieldDescriptor.Builder builder22 = FieldDescriptor.builder("onDeviceSegmentationLogEvent");
        zzdg zzdg22 = new zzdg();
        zzdg22.zza(45);
        zzw = builder22.withProperty(zzdg22.zzb()).build();
        FieldDescriptor.Builder builder23 = FieldDescriptor.builder("onDeviceSmartReplyLogEvent");
        zzdg zzdg23 = new zzdg();
        zzdg23.zza(19);
        zzx = builder23.withProperty(zzdg23.zzb()).build();
        FieldDescriptor.Builder builder24 = FieldDescriptor.builder("onDeviceLanguageIdentificationLogEvent");
        zzdg zzdg24 = new zzdg();
        zzdg24.zza(21);
        zzy = builder24.withProperty(zzdg24.zzb()).build();
        FieldDescriptor.Builder builder25 = FieldDescriptor.builder("onDeviceTranslationLogEvent");
        zzdg zzdg25 = new zzdg();
        zzdg25.zza(22);
        zzz = builder25.withProperty(zzdg25.zzb()).build();
        FieldDescriptor.Builder builder26 = FieldDescriptor.builder("cloudFaceDetectionLogEvent");
        zzdg zzdg26 = new zzdg();
        zzdg26.zza(8);
        zzA = builder26.withProperty(zzdg26.zzb()).build();
        FieldDescriptor.Builder builder27 = FieldDescriptor.builder("cloudCropHintDetectionLogEvent");
        zzdg zzdg27 = new zzdg();
        zzdg27.zza(9);
        zzB = builder27.withProperty(zzdg27.zzb()).build();
        FieldDescriptor.Builder builder28 = FieldDescriptor.builder("cloudDocumentTextDetectionLogEvent");
        zzdg zzdg28 = new zzdg();
        zzdg28.zza(10);
        zzC = builder28.withProperty(zzdg28.zzb()).build();
        FieldDescriptor.Builder builder29 = FieldDescriptor.builder("cloudImagePropertiesDetectionLogEvent");
        zzdg zzdg29 = new zzdg();
        zzdg29.zza(11);
        zzD = builder29.withProperty(zzdg29.zzb()).build();
        FieldDescriptor.Builder builder30 = FieldDescriptor.builder("cloudImageLabelDetectionLogEvent");
        zzdg zzdg30 = new zzdg();
        zzdg30.zza(12);
        zzE = builder30.withProperty(zzdg30.zzb()).build();
        FieldDescriptor.Builder builder31 = FieldDescriptor.builder("cloudLandmarkDetectionLogEvent");
        zzdg zzdg31 = new zzdg();
        zzdg31.zza(13);
        zzF = builder31.withProperty(zzdg31.zzb()).build();
        FieldDescriptor.Builder builder32 = FieldDescriptor.builder("cloudLogoDetectionLogEvent");
        zzdg zzdg32 = new zzdg();
        zzdg32.zza(14);
        zzG = builder32.withProperty(zzdg32.zzb()).build();
        FieldDescriptor.Builder builder33 = FieldDescriptor.builder("cloudSafeSearchDetectionLogEvent");
        zzdg zzdg33 = new zzdg();
        zzdg33.zza(15);
        zzH = builder33.withProperty(zzdg33.zzb()).build();
        FieldDescriptor.Builder builder34 = FieldDescriptor.builder("cloudTextDetectionLogEvent");
        zzdg zzdg34 = new zzdg();
        zzdg34.zza(16);
        zzI = builder34.withProperty(zzdg34.zzb()).build();
        FieldDescriptor.Builder builder35 = FieldDescriptor.builder("cloudWebSearchDetectionLogEvent");
        zzdg zzdg35 = new zzdg();
        zzdg35.zza(17);
        zzJ = builder35.withProperty(zzdg35.zzb()).build();
        FieldDescriptor.Builder builder36 = FieldDescriptor.builder("automlImageLabelingCreateLogEvent");
        zzdg zzdg36 = new zzdg();
        zzdg36.zza(23);
        zzK = builder36.withProperty(zzdg36.zzb()).build();
        FieldDescriptor.Builder builder37 = FieldDescriptor.builder("automlImageLabelingLoadLogEvent");
        zzdg zzdg37 = new zzdg();
        zzdg37.zza(24);
        zzL = builder37.withProperty(zzdg37.zzb()).build();
        FieldDescriptor.Builder builder38 = FieldDescriptor.builder("automlImageLabelingInferenceLogEvent");
        zzdg zzdg38 = new zzdg();
        zzdg38.zza(25);
        zzM = builder38.withProperty(zzdg38.zzb()).build();
        FieldDescriptor.Builder builder39 = FieldDescriptor.builder("isModelDownloadedLogEvent");
        zzdg zzdg39 = new zzdg();
        zzdg39.zza(39);
        zzN = builder39.withProperty(zzdg39.zzb()).build();
        FieldDescriptor.Builder builder40 = FieldDescriptor.builder("deleteModelLogEvent");
        zzdg zzdg40 = new zzdg();
        zzdg40.zza(40);
        zzO = builder40.withProperty(zzdg40.zzb()).build();
        FieldDescriptor.Builder builder41 = FieldDescriptor.builder("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzdg zzdg41 = new zzdg();
        zzdg41.zza(30);
        zzP = builder41.withProperty(zzdg41.zzb()).build();
        FieldDescriptor.Builder builder42 = FieldDescriptor.builder("aggregatedCustomModelInferenceLogEvent");
        zzdg zzdg42 = new zzdg();
        zzdg42.zza(31);
        zzQ = builder42.withProperty(zzdg42.zzb()).build();
        FieldDescriptor.Builder builder43 = FieldDescriptor.builder("aggregatedOnDeviceFaceDetectionLogEvent");
        zzdg zzdg43 = new zzdg();
        zzdg43.zza(32);
        zzR = builder43.withProperty(zzdg43.zzb()).build();
        FieldDescriptor.Builder builder44 = FieldDescriptor.builder("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzdg zzdg44 = new zzdg();
        zzdg44.zza(33);
        zzS = builder44.withProperty(zzdg44.zzb()).build();
        FieldDescriptor.Builder builder45 = FieldDescriptor.builder("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzdg zzdg45 = new zzdg();
        zzdg45.zza(34);
        zzT = builder45.withProperty(zzdg45.zzb()).build();
        FieldDescriptor.Builder builder46 = FieldDescriptor.builder("aggregatedOnDeviceObjectInferenceLogEvent");
        zzdg zzdg46 = new zzdg();
        zzdg46.zza(35);
        zzU = builder46.withProperty(zzdg46.zzb()).build();
        FieldDescriptor.Builder builder47 = FieldDescriptor.builder("aggregatedOnDeviceTextDetectionLogEvent");
        zzdg zzdg47 = new zzdg();
        zzdg47.zza(36);
        zzV = builder47.withProperty(zzdg47.zzb()).build();
        FieldDescriptor.Builder builder48 = FieldDescriptor.builder("aggregatedOnDevicePoseDetectionLogEvent");
        zzdg zzdg48 = new zzdg();
        zzdg48.zza(46);
        zzW = builder48.withProperty(zzdg48.zzb()).build();
        FieldDescriptor.Builder builder49 = FieldDescriptor.builder("aggregatedOnDeviceSegmentationLogEvent");
        zzdg zzdg49 = new zzdg();
        zzdg49.zza(47);
        zzX = builder49.withProperty(zzdg49.zzb()).build();
        FieldDescriptor.Builder builder50 = FieldDescriptor.builder("pipelineAccelerationInferenceEvents");
        zzdg zzdg50 = new zzdg();
        zzdg50.zza(69);
        zzY = builder50.withProperty(zzdg50.zzb()).build();
        FieldDescriptor.Builder builder51 = FieldDescriptor.builder("remoteConfigLogEvent");
        zzdg zzdg51 = new zzdg();
        zzdg51.zza(42);
        zzZ = builder51.withProperty(zzdg51.zzb()).build();
        FieldDescriptor.Builder builder52 = FieldDescriptor.builder("inputImageConstructionLogEvent");
        zzdg zzdg52 = new zzdg();
        zzdg52.zza(50);
        zzaa = builder52.withProperty(zzdg52.zzb()).build();
        FieldDescriptor.Builder builder53 = FieldDescriptor.builder("leakedHandleEvent");
        zzdg zzdg53 = new zzdg();
        zzdg53.zza(51);
        zzab = builder53.withProperty(zzdg53.zzb()).build();
        FieldDescriptor.Builder builder54 = FieldDescriptor.builder("cameraSourceLogEvent");
        zzdg zzdg54 = new zzdg();
        zzdg54.zza(52);
        zzac = builder54.withProperty(zzdg54.zzb()).build();
        FieldDescriptor.Builder builder55 = FieldDescriptor.builder("imageLabelOptionalModuleLogEvent");
        zzdg zzdg55 = new zzdg();
        zzdg55.zza(53);
        zzad = builder55.withProperty(zzdg55.zzb()).build();
        FieldDescriptor.Builder builder56 = FieldDescriptor.builder("languageIdentificationOptionalModuleLogEvent");
        zzdg zzdg56 = new zzdg();
        zzdg56.zza(54);
        zzae = builder56.withProperty(zzdg56.zzb()).build();
        FieldDescriptor.Builder builder57 = FieldDescriptor.builder("faceDetectionOptionalModuleLogEvent");
        zzdg zzdg57 = new zzdg();
        zzdg57.zza(60);
        zzaf = builder57.withProperty(zzdg57.zzb()).build();
        FieldDescriptor.Builder builder58 = FieldDescriptor.builder("documentDetectionOptionalModuleLogEvent");
        zzdg zzdg58 = new zzdg();
        zzdg58.zza(85);
        zzag = builder58.withProperty(zzdg58.zzb()).build();
        FieldDescriptor.Builder builder59 = FieldDescriptor.builder("documentCroppingOptionalModuleLogEvent");
        zzdg zzdg59 = new zzdg();
        zzdg59.zza(86);
        zzah = builder59.withProperty(zzdg59.zzb()).build();
        FieldDescriptor.Builder builder60 = FieldDescriptor.builder("documentEnhancementOptionalModuleLogEvent");
        zzdg zzdg60 = new zzdg();
        zzdg60.zza(87);
        zzai = builder60.withProperty(zzdg60.zzb()).build();
        FieldDescriptor.Builder builder61 = FieldDescriptor.builder("nlClassifierOptionalModuleLogEvent");
        zzdg zzdg61 = new zzdg();
        zzdg61.zza(55);
        zzaj = builder61.withProperty(zzdg61.zzb()).build();
        FieldDescriptor.Builder builder62 = FieldDescriptor.builder("nlClassifierClientLibraryLogEvent");
        zzdg zzdg62 = new zzdg();
        zzdg62.zza(56);
        zzak = builder62.withProperty(zzdg62.zzb()).build();
        FieldDescriptor.Builder builder63 = FieldDescriptor.builder("accelerationAllowlistLogEvent");
        zzdg zzdg63 = new zzdg();
        zzdg63.zza(57);
        zzal = builder63.withProperty(zzdg63.zzb()).build();
        FieldDescriptor.Builder builder64 = FieldDescriptor.builder("toxicityDetectionCreateEvent");
        zzdg zzdg64 = new zzdg();
        zzdg64.zza(62);
        zzam = builder64.withProperty(zzdg64.zzb()).build();
        FieldDescriptor.Builder builder65 = FieldDescriptor.builder("toxicityDetectionLoadEvent");
        zzdg zzdg65 = new zzdg();
        zzdg65.zza(63);
        zzan = builder65.withProperty(zzdg65.zzb()).build();
        FieldDescriptor.Builder builder66 = FieldDescriptor.builder("toxicityDetectionInferenceEvent");
        zzdg zzdg66 = new zzdg();
        zzdg66.zza(64);
        zzao = builder66.withProperty(zzdg66.zzb()).build();
        FieldDescriptor.Builder builder67 = FieldDescriptor.builder("barcodeDetectionOptionalModuleLogEvent");
        zzdg zzdg67 = new zzdg();
        zzdg67.zza(65);
        zzap = builder67.withProperty(zzdg67.zzb()).build();
        FieldDescriptor.Builder builder68 = FieldDescriptor.builder("customImageLabelOptionalModuleLogEvent");
        zzdg zzdg68 = new zzdg();
        zzdg68.zza(66);
        zzaq = builder68.withProperty(zzdg68.zzb()).build();
        FieldDescriptor.Builder builder69 = FieldDescriptor.builder("codeScannerScanApiEvent");
        zzdg zzdg69 = new zzdg();
        zzdg69.zza(67);
        zzar = builder69.withProperty(zzdg69.zzb()).build();
        FieldDescriptor.Builder builder70 = FieldDescriptor.builder("codeScannerOptionalModuleEvent");
        zzdg zzdg70 = new zzdg();
        zzdg70.zza(68);
        zzas = builder70.withProperty(zzdg70.zzb()).build();
        FieldDescriptor.Builder builder71 = FieldDescriptor.builder("onDeviceExplicitContentCreateLogEvent");
        zzdg zzdg71 = new zzdg();
        zzdg71.zza(70);
        zzat = builder71.withProperty(zzdg71.zzb()).build();
        FieldDescriptor.Builder builder72 = FieldDescriptor.builder("onDeviceExplicitContentLoadLogEvent");
        zzdg zzdg72 = new zzdg();
        zzdg72.zza(71);
        zzau = builder72.withProperty(zzdg72.zzb()).build();
        FieldDescriptor.Builder builder73 = FieldDescriptor.builder("onDeviceExplicitContentInferenceLogEvent");
        zzdg zzdg73 = new zzdg();
        zzdg73.zza(72);
        zzav = builder73.withProperty(zzdg73.zzb()).build();
        FieldDescriptor.Builder builder74 = FieldDescriptor.builder("aggregatedOnDeviceExplicitContentLogEvent");
        zzdg zzdg74 = new zzdg();
        zzdg74.zza(73);
        zzaw = builder74.withProperty(zzdg74.zzb()).build();
        FieldDescriptor.Builder builder75 = FieldDescriptor.builder("onDeviceFaceMeshCreateLogEvent");
        zzdg zzdg75 = new zzdg();
        zzdg75.zza(74);
        zzax = builder75.withProperty(zzdg75.zzb()).build();
        FieldDescriptor.Builder builder76 = FieldDescriptor.builder("onDeviceFaceMeshLoadLogEvent");
        zzdg zzdg76 = new zzdg();
        zzdg76.zza(75);
        zzay = builder76.withProperty(zzdg76.zzb()).build();
        FieldDescriptor.Builder builder77 = FieldDescriptor.builder("onDeviceFaceMeshLogEvent");
        zzdg zzdg77 = new zzdg();
        zzdg77.zza(76);
        zzaz = builder77.withProperty(zzdg77.zzb()).build();
        FieldDescriptor.Builder builder78 = FieldDescriptor.builder("aggregatedOnDeviceFaceMeshLogEvent");
        zzdg zzdg78 = new zzdg();
        zzdg78.zza(77);
        zzaA = builder78.withProperty(zzdg78.zzb()).build();
        FieldDescriptor.Builder builder79 = FieldDescriptor.builder("smartReplyOptionalModuleLogEvent");
        zzdg zzdg79 = new zzdg();
        zzdg79.zza(78);
        zzaB = builder79.withProperty(zzdg79.zzb()).build();
        FieldDescriptor.Builder builder80 = FieldDescriptor.builder("textDetectionOptionalModuleLogEvent");
        zzdg zzdg80 = new zzdg();
        zzdg80.zza(80);
        zzaC = builder80.withProperty(zzdg80.zzb()).build();
        FieldDescriptor.Builder builder81 = FieldDescriptor.builder("onDeviceImageQualityAnalysisCreateLogEvent");
        zzdg zzdg81 = new zzdg();
        zzdg81.zza(81);
        zzaD = builder81.withProperty(zzdg81.zzb()).build();
        FieldDescriptor.Builder builder82 = FieldDescriptor.builder("onDeviceImageQualityAnalysisLoadLogEvent");
        zzdg zzdg82 = new zzdg();
        zzdg82.zza(82);
        zzaE = builder82.withProperty(zzdg82.zzb()).build();
        FieldDescriptor.Builder builder83 = FieldDescriptor.builder("onDeviceImageQualityAnalysisLogEvent");
        zzdg zzdg83 = new zzdg();
        zzdg83.zza(83);
        zzaF = builder83.withProperty(zzdg83.zzb()).build();
        FieldDescriptor.Builder builder84 = FieldDescriptor.builder("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzdg zzdg84 = new zzdg();
        zzdg84.zza(84);
        zzaG = builder84.withProperty(zzdg84.zzb()).build();
        FieldDescriptor.Builder builder85 = FieldDescriptor.builder("imageQualityAnalysisOptionalModuleLogEvent");
        zzdg zzdg85 = new zzdg();
        zzdg85.zza(88);
        zzaH = builder85.withProperty(zzdg85.zzb()).build();
        FieldDescriptor.Builder builder86 = FieldDescriptor.builder("imageCaptioningOptionalModuleLogEvent");
        zzdg zzdg86 = new zzdg();
        zzdg86.zza(89);
        zzaI = builder86.withProperty(zzdg86.zzb()).build();
        FieldDescriptor.Builder builder87 = FieldDescriptor.builder("onDeviceImageCaptioningCreateLogEvent");
        zzdg zzdg87 = new zzdg();
        zzdg87.zza(90);
        zzaJ = builder87.withProperty(zzdg87.zzb()).build();
        FieldDescriptor.Builder builder88 = FieldDescriptor.builder("onDeviceImageCaptioningLoadLogEvent");
        zzdg zzdg88 = new zzdg();
        zzdg88.zza(91);
        zzaK = builder88.withProperty(zzdg88.zzb()).build();
        FieldDescriptor.Builder builder89 = FieldDescriptor.builder("onDeviceImageCaptioningInferenceLogEvent");
        zzdg zzdg89 = new zzdg();
        zzdg89.zza(92);
        zzaL = builder89.withProperty(zzdg89.zzb()).build();
        FieldDescriptor.Builder builder90 = FieldDescriptor.builder("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzdg zzdg90 = new zzdg();
        zzdg90.zza(93);
        zzaM = builder90.withProperty(zzdg90.zzb()).build();
        FieldDescriptor.Builder builder91 = FieldDescriptor.builder("onDeviceDocumentDetectionCreateLogEvent");
        zzdg zzdg91 = new zzdg();
        zzdg91.zza(94);
        zzaN = builder91.withProperty(zzdg91.zzb()).build();
        FieldDescriptor.Builder builder92 = FieldDescriptor.builder("onDeviceDocumentDetectionLoadLogEvent");
        zzdg zzdg92 = new zzdg();
        zzdg92.zza(95);
        zzaO = builder92.withProperty(zzdg92.zzb()).build();
        FieldDescriptor.Builder builder93 = FieldDescriptor.builder("onDeviceDocumentDetectionLogEvent");
        zzdg zzdg93 = new zzdg();
        zzdg93.zza(96);
        zzaP = builder93.withProperty(zzdg93.zzb()).build();
        FieldDescriptor.Builder builder94 = FieldDescriptor.builder("aggregatedOnDeviceDocumentDetectionLogEvent");
        zzdg zzdg94 = new zzdg();
        zzdg94.zza(97);
        zzaQ = builder94.withProperty(zzdg94.zzb()).build();
        FieldDescriptor.Builder builder95 = FieldDescriptor.builder("onDeviceDocumentCroppingCreateLogEvent");
        zzdg zzdg95 = new zzdg();
        zzdg95.zza(98);
        zzaR = builder95.withProperty(zzdg95.zzb()).build();
        FieldDescriptor.Builder builder96 = FieldDescriptor.builder("onDeviceDocumentCroppingLoadLogEvent");
        zzdg zzdg96 = new zzdg();
        zzdg96.zza(99);
        zzaS = builder96.withProperty(zzdg96.zzb()).build();
        FieldDescriptor.Builder builder97 = FieldDescriptor.builder("onDeviceDocumentCroppingLogEvent");
        zzdg zzdg97 = new zzdg();
        zzdg97.zza(100);
        zzaT = builder97.withProperty(zzdg97.zzb()).build();
        FieldDescriptor.Builder builder98 = FieldDescriptor.builder("aggregatedOnDeviceDocumentCroppingLogEvent");
        zzdg zzdg98 = new zzdg();
        zzdg98.zza(101);
        zzaU = builder98.withProperty(zzdg98.zzb()).build();
        FieldDescriptor.Builder builder99 = FieldDescriptor.builder("onDeviceDocumentEnhancementCreateLogEvent");
        zzdg zzdg99 = new zzdg();
        zzdg99.zza(102);
        zzaV = builder99.withProperty(zzdg99.zzb()).build();
        FieldDescriptor.Builder builder100 = FieldDescriptor.builder("onDeviceDocumentEnhancementLoadLogEvent");
        zzdg zzdg100 = new zzdg();
        zzdg100.zza(103);
        zzaW = builder100.withProperty(zzdg100.zzb()).build();
        FieldDescriptor.Builder builder101 = FieldDescriptor.builder("onDeviceDocumentEnhancementLogEvent");
        zzdg zzdg101 = new zzdg();
        zzdg101.zza(104);
        zzaX = builder101.withProperty(zzdg101.zzb()).build();
        FieldDescriptor.Builder builder102 = FieldDescriptor.builder("aggregatedOnDeviceDocumentEnhancementLogEvent");
        zzdg zzdg102 = new zzdg();
        zzdg102.zza(105);
        zzaY = builder102.withProperty(zzdg102.zzb()).build();
    }

    private zzih() {
    }

    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) throws IOException {
        zznh zznh = (zznh) obj;
        ObjectEncoderContext objectEncoderContext = (ObjectEncoderContext) obj2;
        objectEncoderContext.add(zzb, (Object) zznh.zzf());
        objectEncoderContext.add(zzc, (Object) zznh.zzc());
        objectEncoderContext.add(zzd, (Object) null);
        objectEncoderContext.add(zze, (Object) zznh.zzb());
        objectEncoderContext.add(zzf, (Object) null);
        objectEncoderContext.add(zzg, (Object) null);
        objectEncoderContext.add(zzh, (Object) null);
        objectEncoderContext.add(zzi, (Object) null);
        objectEncoderContext.add(zzj, (Object) null);
        objectEncoderContext.add(zzk, (Object) null);
        objectEncoderContext.add(zzl, (Object) null);
        objectEncoderContext.add(zzm, (Object) null);
        objectEncoderContext.add(zzn, (Object) zznh.zzd());
        objectEncoderContext.add(zzo, (Object) zznh.zze());
        objectEncoderContext.add(zzp, (Object) null);
        objectEncoderContext.add(zzq, (Object) null);
        objectEncoderContext.add(zzr, (Object) null);
        objectEncoderContext.add(zzs, (Object) null);
        objectEncoderContext.add(zzt, (Object) null);
        objectEncoderContext.add(zzu, (Object) null);
        objectEncoderContext.add(zzv, (Object) null);
        objectEncoderContext.add(zzw, (Object) null);
        objectEncoderContext.add(zzx, (Object) null);
        objectEncoderContext.add(zzy, (Object) null);
        objectEncoderContext.add(zzz, (Object) null);
        objectEncoderContext.add(zzA, (Object) null);
        objectEncoderContext.add(zzB, (Object) null);
        objectEncoderContext.add(zzC, (Object) null);
        objectEncoderContext.add(zzD, (Object) null);
        objectEncoderContext.add(zzE, (Object) null);
        objectEncoderContext.add(zzF, (Object) null);
        objectEncoderContext.add(zzG, (Object) null);
        objectEncoderContext.add(zzH, (Object) null);
        objectEncoderContext.add(zzI, (Object) null);
        objectEncoderContext.add(zzJ, (Object) null);
        objectEncoderContext.add(zzK, (Object) null);
        objectEncoderContext.add(zzL, (Object) null);
        objectEncoderContext.add(zzM, (Object) null);
        objectEncoderContext.add(zzN, (Object) null);
        objectEncoderContext.add(zzO, (Object) null);
        objectEncoderContext.add(zzP, (Object) null);
        objectEncoderContext.add(zzQ, (Object) null);
        objectEncoderContext.add(zzR, (Object) null);
        objectEncoderContext.add(zzS, (Object) zznh.zza());
        objectEncoderContext.add(zzT, (Object) null);
        objectEncoderContext.add(zzU, (Object) null);
        objectEncoderContext.add(zzV, (Object) null);
        objectEncoderContext.add(zzW, (Object) null);
        objectEncoderContext.add(zzX, (Object) null);
        objectEncoderContext.add(zzY, (Object) null);
        objectEncoderContext.add(zzZ, (Object) null);
        objectEncoderContext.add(zzaa, (Object) null);
        objectEncoderContext.add(zzab, (Object) null);
        objectEncoderContext.add(zzac, (Object) null);
        objectEncoderContext.add(zzad, (Object) null);
        objectEncoderContext.add(zzae, (Object) null);
        objectEncoderContext.add(zzaf, (Object) null);
        objectEncoderContext.add(zzag, (Object) null);
        objectEncoderContext.add(zzah, (Object) null);
        objectEncoderContext.add(zzai, (Object) null);
        objectEncoderContext.add(zzaj, (Object) null);
        objectEncoderContext.add(zzak, (Object) null);
        objectEncoderContext.add(zzal, (Object) null);
        objectEncoderContext.add(zzam, (Object) null);
        objectEncoderContext.add(zzan, (Object) null);
        objectEncoderContext.add(zzao, (Object) null);
        objectEncoderContext.add(zzap, (Object) null);
        objectEncoderContext.add(zzaq, (Object) null);
        objectEncoderContext.add(zzar, (Object) null);
        objectEncoderContext.add(zzas, (Object) null);
        objectEncoderContext.add(zzat, (Object) null);
        objectEncoderContext.add(zzau, (Object) null);
        objectEncoderContext.add(zzav, (Object) null);
        objectEncoderContext.add(zzaw, (Object) null);
        objectEncoderContext.add(zzax, (Object) null);
        objectEncoderContext.add(zzay, (Object) null);
        objectEncoderContext.add(zzaz, (Object) null);
        objectEncoderContext.add(zzaA, (Object) null);
        objectEncoderContext.add(zzaB, (Object) null);
        objectEncoderContext.add(zzaC, (Object) null);
        objectEncoderContext.add(zzaD, (Object) null);
        objectEncoderContext.add(zzaE, (Object) null);
        objectEncoderContext.add(zzaF, (Object) null);
        objectEncoderContext.add(zzaG, (Object) null);
        objectEncoderContext.add(zzaH, (Object) null);
        objectEncoderContext.add(zzaI, (Object) null);
        objectEncoderContext.add(zzaJ, (Object) null);
        objectEncoderContext.add(zzaK, (Object) null);
        objectEncoderContext.add(zzaL, (Object) null);
        objectEncoderContext.add(zzaM, (Object) null);
        objectEncoderContext.add(zzaN, (Object) null);
        objectEncoderContext.add(zzaO, (Object) null);
        objectEncoderContext.add(zzaP, (Object) null);
        objectEncoderContext.add(zzaQ, (Object) null);
        objectEncoderContext.add(zzaR, (Object) null);
        objectEncoderContext.add(zzaS, (Object) null);
        objectEncoderContext.add(zzaT, (Object) null);
        objectEncoderContext.add(zzaU, (Object) null);
        objectEncoderContext.add(zzaV, (Object) null);
        objectEncoderContext.add(zzaW, (Object) null);
        objectEncoderContext.add(zzaX, (Object) null);
        objectEncoderContext.add(zzaY, (Object) null);
    }
}
